name: proyecto_movil
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  get_storage: ^2.1.1
  http: ^1.3.0
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: lib/assets/logo-cuc.png

  color_dark: "#121212"
  image_dark: lib/assets/logo-cuc.png

  android_12:
    image: lib/assets/logo-cuc.png
    icon_background_color: "#ffffff"
    image_dark: lib/assets/logo-cuc.png
    icon_background_color_dark: "#121212"
  android: true
  ios: true
  web: false

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo-cuc.png"
  adaptive_icon_background: "#ffffff" # Solo para Android 8.0+

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo-cuc.png

